### ISSUE TITLE
Experimental prism does not load

### ISSUE THREAD

**Issue by netoneko** [orbs-network/prism#6]
Connection hangs forever.

Docker logs:

```
(node:1) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/opt/prism/dist/statics/manifest.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.getManifest (/opt/prism/dist/server-root/server/routes/manifest-manager.js:20:26)
    at router.get (/opt/prism/dist/server-root/server/routes/pages-router.js:11:55)
    at Layer.handle [as handle_request] (/opt/prism/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/prism/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/prism/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/prism/node_modules/express/lib/router/layer.js:95:5)
    at /opt/prism/node_modules/express/lib/router/index.js:281:22
    at param (/opt/prism/node_modules/express/lib/router/index.js:354:14)
    at param (/opt/prism/node_modules/express/lib/router/index.js:365:14)
    at param (/opt/prism/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/opt/prism/node_modules/express/lib/router/index.js:410:3)
    at next (/opt/prism/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/opt/prism/node_modules/express/lib/router/index.js:174:3)
    at router (/opt/prism/node_modules/express/lib/router/index.js:47:12)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```

**Comment by gilamran** [comment]
Fixed on the latest experimental
